status = [
  "test-os (ubuntu-latest)",
  "test-os (windows-latest)",
  "test-os (macos-latest)",
  "buildkite/rootsolvers-ci",
  "docs-build"
]
delete_merged_branches = true
timeout_sec = 86400
block_labels = [ "do-not-merge-yet" ]
cut_body_after = "<!--"
