name = "RootSolvers"
uuid = "7181ea78-2dcb-4de3-ab41-2b8ab5a31e74"
authors = ["CliMA Contributors <clima-software@caltech.edu>"]
version = "0.4.2"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[compat]
ForwardDiff = "0.10"
julia = "1.6"
