name = "RootSolvers"
uuid = "7181ea78-2dcb-4de3-ab41-2b8ab5a31e74"
authors = ["CliMA Contributors <clima-software@caltech.edu>"]
version = "0.4.4"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
ForwardDiff = "0.10, 1"
Printf = "<0.0.1, 1"
julia = "1.6"
