name = "RootSolvers"
uuid = "7181ea78-2dcb-4de3-ab41-2b8ab5a31e74"
authors = ["Charles Kawczynski <kawczynski.charles@gmail.com>"]
version = "0.2.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DocStringExtensions = "~0.8.1"
ForwardDiff = "~0.10.9"
julia = "1.3"
