agents:
  queue: central
  slurm_mem: 8G
  modules: julia/1.9.3 cuda/12.2

env:
  JULIA_VERSION: "1.9.3"
  OPENBLAS_NUM_THREADS: 1
  CUDA_VERSION: "12.2"
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_CPU_TARGET: 'broadwell;skylake'

steps:
  - label: "init environment :computer:"
    key: "init_env"
    command:
      - echo "--- Instantiate test env"
      - julia --project=test -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true); Pkg.status()'
    agents:
      slurm_ntasks: 1
      slurm_gpus: 1

  - wait

  - label: "CPU tests"
    command:
      - "julia --project=test test/runtests.jl"
    agents:
      config: cpu
      slurm_ntasks: 1

  - label: "GPU tests"
    command:
      - "julia --project=test test/runtests.jl CuArray"
    agents:
      slurm_ntasks: 1
      slurm_gpus: 1
