env:
  JULIA_VERSION: "1.9.3"
  CUDA_VERSION: "12.2"

steps:
  - label: "init cpu env"
    key: "init_cpu_env"
    command:
      - echo "--- Instantiate project cpu"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile(;strict=true)'"
      - "julia --project -e 'using Pkg; Pkg.status()'"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - label: "init gpu env"
    key: "init_gpu_env"
    command:
      - echo "--- Instantiate project gpu"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile(;strict=true)'"
      - echo "--- Instantiate test gpu"
      - "julia --project=test -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=test -e 'using Pkg; Pkg.precompile(;strict=true)'"
      - "julia --project=test -e 'using CUDA; CUDA.versioninfo()'"
      - "julia --project=test -e 'using CUDA; CUDA.precompile_runtime()'"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - label: "CPU tests"
    command:
      - "julia --project -e 'using Pkg; Pkg.test()'"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "GPU tests"
    command:
      - "julia --project -e 'using Pkg; Pkg.test(;test_args=[\"CuArray\"])'"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gpus: 1
