agents:
  queue: new-central
  slurm_mem: 3G
  modules: climacommon/2024_10_09
  slurm_time: '00:20:00'

env:
  OPENBLAS_NUM_THREADS: 1

steps:
  - label: "init environment :computer:"
    key: "init_env"
    command:
      - echo "--- Instantiate test env"
      - julia --project=test -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true); Pkg.status()'
    agents:
      slurm_ntasks: 1
      slurm_gpus: 1

  - wait

  - label: "CPU tests"
    command:
      - "julia --project=test test/runtests.jl"
    agents:
      slurm_ntasks: 1
    timeout_in_minutes: 60

  - label: "GPU tests"
    command:
      - "julia --project=test test/runtests.jl CuArray"
    agents:
      slurm_ntasks: 1
      slurm_gpus: 1
    timeout_in_minutes: 60
